# Generated by Django 2.2.2 on 2019-07-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnings', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['tournament', 'player'],
            },
        ),
        migrations.CreateModel(
            name='GroupBPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnings', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['tournament', 'player'],
            },
        ),
        migrations.CreateModel(
            name='GroupCPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnings', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['tournament', 'player'],
            },
        ),
        migrations.CreateModel(
            name='GroupDPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnings', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['tournament', 'player'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('total_winnings', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Person')),
                ('pick_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.GroupAPlayer')),
                ('pick_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.GroupBPlayer')),
                ('pick_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.GroupCPlayer')),
                ('pick_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.GroupDPlayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='groupdplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='groupdplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='groupcplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='groupcplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='groupbplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='groupbplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='groupaplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='groupaplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
