# Generated by Django 2.2.2 on 2019-08-05 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentpick',
            name='pick_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_a', to='tournaments.TournamentPlayer'),
        ),
        migrations.AlterField(
            model_name='tournamentpick',
            name='pick_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_b', to='tournaments.TournamentPlayer'),
        ),
        migrations.AlterField(
            model_name='tournamentpick',
            name='pick_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_c', to='tournaments.TournamentPlayer'),
        ),
        migrations.AlterField(
            model_name='tournamentpick',
            name='pick_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_d', to='tournaments.TournamentPlayer'),
        ),
    ]
