# Generated by Django 2.2.2 on 2019-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpick',
            name='total_winnings',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
