# Generated by Django 2.2.2 on 2019-07-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupaplayer',
            options={'ordering': ['tournament', 'player']},
        ),
        migrations.AlterModelOptions(
            name='groupbplayer',
            options={'ordering': ['tournament', 'player']},
        ),
        migrations.AlterModelOptions(
            name='groupcplayer',
            options={'ordering': ['tournament', 'player']},
        ),
        migrations.AlterModelOptions(
            name='groupdplayer',
            options={'ordering': ['tournament', 'player']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['name']},
        ),
    ]
